name: conv-mamba
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nclibz
dependencies:
  - conda-forge::python=3.12.2
  - conda-forge::pip=24.0
  - conda-forge::cudatoolkit-dev=11.7.0
  - conda-forge::numpy=1.26.4
  - conda-forge::lightning=2.2.1
  - conda-forge::scikit-learn=1.4.1
  - conda-forge::scipy=1.12.0
  - conda-forge::tensorboard=2.16.2
  - conda-forge::timm=0.9.16
  - pytorch::pytorch=2.2.1
  - pytorch::torchvision=0.17.1
  - nclibz::torch-tb-profiler=0.2.1
  - pip:
    - -e .
    - "jsonargparse[signatures]==4.27.7"
